pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh './mvnw test'
            }
        }
	stage('Deploy to Tomcat') {
	    steps {
                sh '''
                    cp target/*.war /opt/deploy/springboot-app.war
                    sudo cp /opt/deploy/springboot-app.war /opt/tomcat/webapps/springboot-app.war
                    sudo systemctl restart tomcat
                '''
		}
	}
	stage('Verify Deployment') {
	    steps {
	       sh '''
        	sleep 10
        	curl -f http://localhost:8081/springboot-app/
        	'''
		}
	}

        stage('Package') {
            steps {
                archiveArtifacts artifacts: 'target/*.war',
                         fingerprint: true
            }
        }
    }

}

